<SELECT id="desplegable" name="localizacion" > 

   <OPTION VALUE="TODAS LAS LOCALIDADES">TODAS LAS LOCALIDADES</OPTION> 

   <OPTION VALUE="Alameda">Alameda</OPTION> 
   <OPTION VALUE="Alcaucín"> Alcaucín </OPTION> 
   <OPTION VALUE="Alfarnate">Alfarnate   </OPTION> 
   <OPTION VALUE="Alfarnatejo"> Alfarnatejo  </OPTION> 
   <OPTION VALUE="Algarrobo"> Algarrobo  </OPTION> 
   <OPTION VALUE="Algatocín"> Algatocín </OPTION> 
   <OPTION VALUE="Alhaurín de la Torre"> Alhaurín de la Torre </OPTION> 
   <OPTION VALUE="Alhaurín el Grande"> Alhaurín el Grande  </OPTION> 
   <OPTION VALUE="Almáchar"> Almáchar  </OPTION> 
   <OPTION VALUE="Almargen">Almargen   </OPTION> 
   <OPTION VALUE="Almogía"> Almogía </OPTION> 
   <OPTION VALUE="Álora"> Álora  </OPTION> 
   <OPTION VALUE="Alozaina"> Alozaina </OPTION> 
   <OPTION VALUE="Alpandeire">Alpandeire  </OPTION> 
   <OPTION VALUE="Antequera">  Antequera </OPTION> 
   <OPTION VALUE="Árchez"> Árchez </OPTION> 
   <OPTION VALUE="Archidona"> Archidona  </OPTION> 
   <OPTION VALUE="Ardales"> Ardales </OPTION> 
   <OPTION VALUE="Arenas"> Arenas </OPTION> 
   <OPTION VALUE="Arriate"> Arriate </OPTION> 
   <OPTION VALUE="Atajate"> Atajate </OPTION> 
   <OPTION VALUE="Benadalid">Benadalid  </OPTION> 
   <OPTION VALUE="Benahavís"> Benahavís </OPTION> 
    <OPTION VALUE="Benajarafe"> Benajarafe </OPTION> 
   <OPTION VALUE="Benalauría">Benalauría  </OPTION> 
   <OPTION VALUE="Benalmádena"> Benalmádena </OPTION> 
   <OPTION VALUE="Benamargosa"> Benamargosa </OPTION> 
   <OPTION VALUE="Benamocarra">Benamocarra  </OPTION> 
   <OPTION VALUE="Benaoján"> Benaoján </OPTION> 
   <OPTION VALUE="Benarrabá"> Benarrabá </OPTION> 
   <OPTION VALUE="El Borge"> El Borge </OPTION> 
   <OPTION VALUE="El Burgo"> El Burgo </OPTION> 
   <OPTION VALUE="Campillos"> Campillos </OPTION> 
   <OPTION VALUE="Canilla de Aceituno">Canilla de Aceituno   </OPTION> 
   <OPTION VALUE="Canillas de Albaida"> Canillas de Albaida </OPTION> 
   <OPTION VALUE="Cañete la Real"> Cañete la Real </OPTION> 
   <OPTION VALUE="Carratraca"> Carratraca </OPTION> 
   <OPTION VALUE="Cartajima">  Cartajima</OPTION> 
   <OPTION VALUE="Cártama"> Cártama </OPTION> 
   <OPTION VALUE="Casabermeja"> Casabermeja </OPTION> 
   <OPTION VALUE="Casarabonela">Casarabonela  </OPTION> 
   <OPTION VALUE="Casares"> Casares </OPTION>
   <OPTION VALUE="Chilches"> Chilches </OPTION>     
   <OPTION VALUE="Coín"> Coín </OPTION> 
   <OPTION VALUE="Colmenar">Colmenar  </OPTION> 
   <OPTION VALUE="Comares"> Comares </OPTION> 
   <OPTION VALUE="Cómpeta">Cómpeta  </OPTION> 
   <OPTION VALUE="Cortes de la Frontera"> Cortes de la Frontera </OPTION> 
   <OPTION VALUE="Cuevas Bajas">Cuevas Bajas  </OPTION> 
   <OPTION VALUE="Cuevas de San Marcos"> Cuevas de San Marcos </OPTION> 
   <OPTION VALUE="Cuevas del Becerro">Cuevas del Becerro   </OPTION> 
   <OPTION VALUE="Cútar"> Cútar </OPTION> 
   <OPTION VALUE="Estepona"> Estepona </OPTION> 
   <OPTION VALUE="Faraján">Faraján  </OPTION> 
   <OPTION VALUE="Frigiliana"> Frigiliana </OPTION> 
   <OPTION VALUE="Fuengirola"> Fuengirola </OPTION> 
   <OPTION VALUE="Fuente de Piedra"> Fuente de Piedra </OPTION> 
   <OPTION VALUE="Gaucín"> Gaucín </OPTION> 
   <OPTION VALUE="Genalguacil"> Genalguacil </OPTION> 
   <OPTION VALUE="Guaro"> Guaro </OPTION> 
   <OPTION VALUE="Humilladero">Humilladero  </OPTION> 
   <OPTION VALUE="Igualeja"> Igualeja </OPTION> 
   <OPTION VALUE="Istán"> Istán </OPTION> 
   <OPTION VALUE="Iznate"> Iznate </OPTION> 
   <OPTION VALUE="Jimera de Líbar"> Jimera de Líbar </OPTION> 
   <OPTION VALUE="Jubrique"> Jubrique </OPTION> 
   <OPTION VALUE="Júzcar">Júzcar  </OPTION> 
   <OPTION VALUE="La Viñuela">  La Viñuela</OPTION> 
   <OPTION VALUE="Macharaviaya"> Macharaviaya </OPTION> 
   <OPTION VALUE="Málaga">Málaga  </OPTION> 
   <OPTION VALUE="Manilva"> Manilva </OPTION> 
   <OPTION VALUE="Marbella"> Marbella </OPTION> 
   <OPTION VALUE="Mijas"> Mijas </OPTION> 
   <OPTION VALUE="Moclinejo"> Moclinejo </OPTION> 
   <OPTION VALUE="Mollina">Mollina  </OPTION> 
   <OPTION VALUE="Monda">Monda  </OPTION> 
   <OPTION VALUE="Montejaque"> Montejaque </OPTION> 
   <OPTION VALUE="Nerja">Nerja  </OPTION> 
   <OPTION VALUE="Ojén"> Ojén </OPTION> 
   <OPTION VALUE="Parauta"> Parauta </OPTION> 
   <OPTION VALUE="Periana"> Periana </OPTION> 
   <OPTION VALUE="Pizarra"> Pizarra </OPTION> 
   <OPTION VALUE="Pujerra"> Pujerra </OPTION> 
   <OPTION VALUE="Rincón de la Victoria"> Rincón de la Victoria </OPTION> 
   <OPTION VALUE="Riogordo"> Riogordo </OPTION> 
   <OPTION VALUE="Ronda"> Ronda </OPTION> 
   <OPTION VALUE="Salares"> Salares </OPTION> 
   <OPTION VALUE="Sayalonga">Sayalonga  </OPTION> 
   <OPTION VALUE="Sedella">Sedella  </OPTION> 
   <OPTION VALUE="Sierra de Yeguas"> Sierra de Yeguas </OPTION> 
   <OPTION VALUE="Teba"> Teba </OPTION> 
   <OPTION VALUE="Tolox"> Tolox </OPTION> 
   <OPTION VALUE="Torremolinos">Torremolinos  </OPTION> 
   <OPTION VALUE="Torrox">Torrox  </OPTION> 
   <OPTION VALUE="Totalán"> Totalán </OPTION> 
   <OPTION VALUE="Valle de Abdalajís"> Valle de Abdalajís </OPTION> 
   <OPTION VALUE="Vélez-Málaga ">Vélez-Málaga   </OPTION> 
   <OPTION VALUE="Villanueva de Algaidas"> Villanueva de Algaidas </OPTION> 
   <OPTION VALUE="Villanueva de la Concepción"> Villanueva de la Concepción </OPTION> 
   <OPTION VALUE="Villanueva de Tapia"> Villanueva de Tapia </OPTION> 
   <OPTION VALUE="Villanueva del Rosario"> Villanueva del Rosario </OPTION> 
   <OPTION VALUE="Villanueva del Trabuco">  Villanueva del Trabuco </OPTION> 
   <OPTION VALUE="Yunquera"> Yunquera  </OPTION> 

   <OPTION VALUE="FUERA DE MÁLAGA">OTRA LOCALIDAD DISTINTA</OPTION>       
   <OPTION VALUE="FUERA DE MÁLAGA">FUERA DE MÁLAGA</OPTION>    

</SELECT>