<?php include ('cabecera_inicio3.php'); ?>


<!-- **************************contenido del div contenido******************** -->      

<h2 > Bienvenid@ </h2>

<p align="left">El dinero es una herramienta artificial para facilitar el intercambio de bienes y servicios. Mucha gente cree que sin dinero no se pueden intercambiar bienes y servicios, pero eso es falso. El problema de las “crisis” es que no se mueve mucho dinero, y se pierden empleos. Eso no significa que la gente sin trabajo no tenga nada que ofrecer a la sociedad, sino que no hay dinero para pagarle sus servicios. Desde tiempo inmemorial la gente sabe intercambiar bienes y servicios sin mediar dinero. En nuestra era, Internet nos facilita esa tarea y es una forma genial de conseguir bienes y servicios sin gastar dinero, pagando con todo lo bueno que podamos ofrecer (nuestro trabajo, nuestras habilidades, nuestra compañía…). En Málaga contamos con la moneda llamada Málaga Común (moneda complementaria de Málaga,. Es un sistema por el que podemos comerciar sin influir en el PIB. En España y el resto del mundo están funcionando cada vez más sistemas de monedas complementarias.  </p>



<p align="left">El dinero es una herramienta artificial para facilitar el intercambio de bienes y servicios. Mucha gente cree que sin dinero no se pueden intercambiar bienes y servicios, pero eso es falso. El problema de las “crisis” es que no se mueve mucho dinero, y se pierden empleos. Eso no significa que la gente sin trabajo no tenga nada que ofrecer a la sociedad, sino que no hay dinero para pagarle sus servicios. Desde tiempo inmemorial la gente sabe intercambiar bienes y servicios sin mediar dinero. En nuestra era, Internet nos facilita esa tarea y es una forma genial de conseguir bienes y servicios sin gastar dinero, pagando con todo lo bueno que podamos ofrecer (nuestro trabajo, nuestras habilidades, nuestra compañía…). En Málaga contamos con la moneda llamada Málaga Común (moneda complementaria de Málaga,. Es un sistema por el que podemos comerciar sin influir en el PIB. En España y el resto del mundo están funcionando cada vez más sistemas de monedas complementarias.  </p>


<p align="left">El dinero es una herramienta artificial para facilitar el intercambio de bienes y servicios. Mucha gente cree que sin dinero no se pueden intercambiar bienes y servicios, pero eso es falso. El problema de las “crisis” es que no se mueve mucho dinero, y se pierden empleos. Eso no significa que la gente sin trabajo no tenga nada que ofrecer a la sociedad, sino que no hay dinero para pagarle sus servicios. Desde tiempo inmemorial la gente sabe intercambiar bienes y servicios sin mediar dinero. En nuestra era, Internet nos facilita esa tarea y es una forma genial de conseguir bienes y servicios sin gastar dinero, pagando con todo lo bueno que podamos ofrecer (nuestro trabajo, nuestras habilidades, nuestra compañía…). En Málaga contamos con la moneda llamada Málaga Común (moneda complementaria de Málaga,. Es un sistema por el que podemos comerciar sin influir en el PIB. En España y el resto del mundo están funcionando cada vez más sistemas de monedas complementarias.  </p>



<p align="left">El dinero es una herramienta artificial para facilitar el intercambio de bienes y servicios. Mucha gente cree que sin dinero no se pueden intercambiar bienes y servicios, pero eso es falso. El problema de las “crisis” es que no se mueve mucho dinero, y se pierden empleos. Eso no significa que la gente sin trabajo no tenga nada que ofrecer a la sociedad, sino que no hay dinero para pagarle sus servicios. Desde tiempo inmemorial la gente sabe intercambiar bienes y servicios sin mediar dinero. En nuestra era, Internet nos facilita esa tarea y es una forma genial de conseguir bienes y servicios sin gastar dinero, pagando con todo lo bueno que podamos ofrecer (nuestro trabajo, nuestras habilidades, nuestra compañía…). En Málaga contamos con la moneda llamada Málaga Común (moneda complementaria de Málaga,. Es un sistema por el que podemos comerciar sin influir en el PIB. En España y el resto del mundo están funcionando cada vez más sistemas de monedas complementarias.  </p>



<p align="left">El dinero es una herramienta artificial para facilitar el intercambio de bienes y servicios. Mucha gente cree que sin dinero no se pueden intercambiar bienes y servicios, pero eso es falso. El problema de las “crisis” es que no se mueve mucho dinero, y se pierden empleos. Eso no significa que la gente sin trabajo no tenga nada que ofrecer a la sociedad, sino que no hay dinero para pagarle sus servicios. Desde tiempo inmemorial la gente sabe intercambiar bienes y servicios sin mediar dinero. En nuestra era, Internet nos facilita esa tarea y es una forma genial de conseguir bienes y servicios sin gastar dinero, pagando con todo lo bueno que podamos ofrecer (nuestro trabajo, nuestras habilidades, nuestra compañía…). En Málaga contamos con la moneda llamada Málaga Común (moneda complementaria de Málaga,. Es un sistema por el que podemos comerciar sin influir en el PIB. En España y el resto del mundo están funcionando cada vez más sistemas de monedas complementarias.  </p>



<p align="left">El dinero es una herramienta artificial para facilitar el intercambio de bienes y servicios. Mucha gente cree que sin dinero no se pueden intercambiar bienes y servicios, pero eso es falso. El problema de las “crisis” es que no se mueve mucho dinero, y se pierden empleos. Eso no significa que la gente sin trabajo no tenga nada que ofrecer a la sociedad, sino que no hay dinero para pagarle sus servicios. Desde tiempo inmemorial la gente sabe intercambiar bienes y servicios sin mediar dinero. En nuestra era, Internet nos facilita esa tarea y es una forma genial de conseguir bienes y servicios sin gastar dinero, pagando con todo lo bueno que podamos ofrecer (nuestro trabajo, nuestras habilidades, nuestra compañía…). En Málaga contamos con la moneda llamada Málaga Común (moneda complementaria de Málaga,. Es un sistema por el que podemos comerciar sin influir en el PIB. En España y el resto del mundo están funcionando cada vez más sistemas de monedas complementarias.  </p>


<p align="left">El dinero es una herramienta artificial para facilitar el intercambio de bienes y servicios. Mucha gente cree que sin dinero no se pueden intercambiar bienes y servicios, pero eso es falso. El problema de las “crisis” es que no se mueve mucho dinero, y se pierden empleos. Eso no significa que la gente sin trabajo no tenga nada que ofrecer a la sociedad, sino que no hay dinero para pagarle sus servicios. Desde tiempo inmemorial la gente sabe intercambiar bienes y servicios sin mediar dinero. En nuestra era, Internet nos facilita esa tarea y es una forma genial de conseguir bienes y servicios sin gastar dinero, pagando con todo lo bueno que podamos ofrecer (nuestro trabajo, nuestras habilidades, nuestra compañía…). En Málaga contamos con la moneda llamada Málaga Común (moneda complementaria de Málaga,. Es un sistema por el que podemos comerciar sin influir en el PIB. En España y el resto del mundo están funcionando cada vez más sistemas de monedas complementarias.  </p>



<p align="left">El dinero es una herramienta artificial para facilitar el intercambio de bienes y servicios. Mucha gente cree que sin dinero no se pueden intercambiar bienes y servicios, pero eso es falso. El problema de las “crisis” es que no se mueve mucho dinero, y se pierden empleos. Eso no significa que la gente sin trabajo no tenga nada que ofrecer a la sociedad, sino que no hay dinero para pagarle sus servicios. Desde tiempo inmemorial la gente sabe intercambiar bienes y servicios sin mediar dinero. En nuestra era, Internet nos facilita esa tarea y es una forma genial de conseguir bienes y servicios sin gastar dinero, pagando con todo lo bueno que podamos ofrecer (nuestro trabajo, nuestras habilidades, nuestra compañía…). En Málaga contamos con la moneda llamada Málaga Común (moneda complementaria de Málaga,. Es un sistema por el que podemos comerciar sin influir en el PIB. En España y el resto del mundo están funcionando cada vez más sistemas de monedas complementarias.  </p>



<p align="left">El dinero es una herramienta artificial para facilitar el intercambio de bienes y servicios. Mucha gente cree que sin dinero no se pueden intercambiar bienes y servicios, pero eso es falso. El problema de las “crisis” es que no se mueve mucho dinero, y se pierden empleos. Eso no significa que la gente sin trabajo no tenga nada que ofrecer a la sociedad, sino que no hay dinero para pagarle sus servicios. Desde tiempo inmemorial la gente sabe intercambiar bienes y servicios sin mediar dinero. En nuestra era, Internet nos facilita esa tarea y es una forma genial de conseguir bienes y servicios sin gastar dinero, pagando con todo lo bueno que podamos ofrecer (nuestro trabajo, nuestras habilidades, nuestra compañía…). En Málaga contamos con la moneda llamada Málaga Común (moneda complementaria de Málaga,. Es un sistema por el que podemos comerciar sin influir en el PIB. En España y el resto del mundo están funcionando cada vez más sistemas de monedas complementarias.  </p>



<p align="left">El dinero es una herramienta artificial para facilitar el intercambio de bienes y servicios. Mucha gente cree que sin dinero no se pueden intercambiar bienes y servicios, pero eso es falso. El problema de las “crisis” es que no se mueve mucho dinero, y se pierden empleos. Eso no significa que la gente sin trabajo no tenga nada que ofrecer a la sociedad, sino que no hay dinero para pagarle sus servicios. Desde tiempo inmemorial la gente sabe intercambiar bienes y servicios sin mediar dinero. En nuestra era, Internet nos facilita esa tarea y es una forma genial de conseguir bienes y servicios sin gastar dinero, pagando con todo lo bueno que podamos ofrecer (nuestro trabajo, nuestras habilidades, nuestra compañía…). En Málaga contamos con la moneda llamada Málaga Común (moneda complementaria de Málaga,. Es un sistema por el que podemos comerciar sin influir en el PIB. En España y el resto del mundo están funcionando cada vez más sistemas de monedas complementarias.  </p>



<p align="left">El dinero es una herramienta artificial para facilitar el intercambio de bienes y servicios. Mucha gente cree que sin dinero no se pueden intercambiar bienes y servicios, pero eso es falso. El problema de las “crisis” es que no se mueve mucho dinero, y se pierden empleos. Eso no significa que la gente sin trabajo no tenga nada que ofrecer a la sociedad, sino que no hay dinero para pagarle sus servicios. Desde tiempo inmemorial la gente sabe intercambiar bienes y servicios sin mediar dinero. En nuestra era, Internet nos facilita esa tarea y es una forma genial de conseguir bienes y servicios sin gastar dinero, pagando con todo lo bueno que podamos ofrecer (nuestro trabajo, nuestras habilidades, nuestra compañía…). En Málaga contamos con la moneda llamada Málaga Común (moneda complementaria de Málaga,. Es un sistema por el que podemos comerciar sin influir en el PIB. En España y el resto del mundo están funcionando cada vez más sistemas de monedas complementarias.  </p>


<!-- **********************fin del contenido del div contenido******************** -->
 

<?php include ('pie3.php'); ?>
